### ISSUE TITLE
Tool no longer works.

### ISSUE THREAD

**Issue by liuzhen2008** [staxmanade/diffXcodeTargets#3]
Probably some dependencies has made some major changes.

The example no longer works, receive this error.
```
> diffXcodeTargets ./testapp.xcodeproj/project.pbxproj
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at Liftoff.buildEnvironment (/usr/local/lib/node_modules/diffxcodetargets/node_modules/liftoff/index.js:110:52)
    at Liftoff.launch (/usr/local/lib/node_modules/diffxcodetargets/node_modules/liftoff/index.js:163:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/diffxcodetargets/bin/index.js:55:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

**Comment by staxmanade** [comment]
Thanks for the report - Mind doing some research and sending a pull request? I'd be happy to publish an update if a fix came in.

**Comment by teameh** [comment]
PR to fix this: https://github.com/staxmanade/diffXcodeTargets/pull/4 :)
